name: Tests de Comandos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Configurar entorno
      run: |
        chmod +x ./tests/*.sh
        
    - name: Ejecutar tests de comandos básicos
      id: test-basicos
      run: ./tests/test_comandos_basicos.sh
      
    - name: Ejecutar tests de redirecciones
      id: test-redirecciones
      run: ./tests/test_redirecciones.sh
      
    - name: Ejecutar tests de pipes
      id: test-pipes
      run: ./tests/test_pipes.sh
      
    - name: Ejecutar tests de directory-info.sh
      id: test-directory-info
      run: |
        chmod +x ./ejercicios/directory-info.sh
        ./tests/test_directory_info.sh
