name: Tests de Comandos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Configurar entorno
      run: |
        echo "Estructura del repositorio:"
        find . -type f -name "*.sh" | sort
        echo "Permisos de los scripts:"
        chmod +x ./tests/*.sh
        chmod +x ./ejercicios/*.sh
        ls -la ./tests/
        ls -la ./ejercicios/
        echo "Contenido de comandos_basicos.sh:"
        cat ./ejercicios/comandos_basicos.sh
        
    - name: Ejecutar tests de comandos básicos (verificación de salida)
      id: test-basicos-output
      continue-on-error: true
      run: |
        echo "Directorio actual: $(pwd)"
        echo "Contenido del directorio tests:"
        ls -la ./tests/
        ./tests/test_comandos_basicos_output.sh
      
    # Generar reporte de resultados
    - name: Generar reporte de tests
      run: |
        echo "# Resultados de los Tests" > test_results.md
        echo "" >> test_results.md
        echo "## Comandos Básicos (Salida)" >> test_results.md
        if [[ "${{ steps.test-basicos-output.outcome }}" == "success" ]]; then
          echo "✅ **Completado**" >> test_results.md
        else
          echo "❌ **Pendiente**" >> test_results.md
        fi
        
    - name: Guardar resultados como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.md
        
    - name: Imprimir resultados en el log
      run: cat test_results.md
